### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by akeohanePing** [chromaui/chromatic-cli#642] opened 2022-09-19 21:40 UTC
Hi there,

Awesome package!
I am curious if Chromatic currently has plans to support React v18?

Thanks

**Comment by ghengeveld** [comment] 2022-09-20 02:54
Hi,

Can you elaborate on what about React v18 is not working for you? There might be some particular Storybook addons that don't work with React 18, but in general Chromatic should not be affected by that.

If you contact us through our in-app chat or by emailing support@chromatic.com, we can help you out quicker and it'll be a private channel.

Closing this because the issue is unrelated to the CLI.

~Gert

**Closed by ghengeveld** 2022-09-20 02:54 UTC
Labels: needs triage
