### ISSUE TITLE
Extraction of storybook stories appears broken since this morning.

### ISSUE THREAD

**Issue by FlorianSipgate** [chromaui/chromatic-cli#858] opened 2023-11-17 09:47 UTC
**Bug report**

Since this morning, uploading our stories using the chromatic CLI does not work and aborts with the following error: 

```
The following error was encountered while running your Storybook:

Cannot destructure property 'provider' of 'undefined' as it is undefined.
```

The same commit worked yesterday.

See also: https://github.com/chromaui/chromatic-cli/issues/703#issuecomment-1815300630

**Comment by kim-fransson** [comment] 2023-11-17 10:45
I can confirm that we have the same issue, tried upgrading chromatic-cli to 9.0.0 but no luck. Our storybook seems fine and I also build it locally with no obvious errors in the logs.

**Comment by dvasyliev** [comment] 2023-11-17 11:27
I have the same issue

```bash
Chromatic CLI v6.17.4
https://www.chromatic.com/docs/cli

  ✔ Authenticated with Chromatic
  ✔ Retrieved git information
  ✔ Collected Storybook metadata
  ✔ Initialized build
  ✔ Storybook built in 19 seconds
  ✔ Publish complete in 22 seconds
  ✖ Verifying your Storybook
    → Failed to publish build
    Test your stories

⚠ Using outdated package
You are using an outdated version of the Chromatic CLI (v6.17.4).
A new major version is available (v9.0.0).
Run yarn upgrade chromatic --latest to upgrade.

✖ Failed to extract stories from your Storybook
This is usually a problem with your published Storybook, not with Chromatic.

Build and open your Storybook locally and check the browser console for errors.
The following error was encountered while running your Storybook:

Cannot destructure property 'provider' of 'undefined' as it is undefined.
```

**Comment by cgbl-90** [comment] 2023-11-17 11:39
@dvasyliev @kim-fransson @FlorianSipgate, thanks for reporting! We're currently looking into this issue.

**Comment by mtzo09-dev** [comment] 2023-11-17 11:59
Same issue here! The Storybook works perfectly, and the build runs without errors

**Comment by sherpadee** [comment] 2023-11-17 13:39
Same issue here! The Storybook works perfectly, and the build runs without errors!

**Comment by darkSalvation** [comment] 2023-11-17 13:39
Same issue here! The Storybook works perfectly, and the build runs without errors!

**Comment by cgbl-90** [comment] 2023-11-17 13:41
Thanks for sharing @mtzo09-dev @sherpadee! We confirmed with other users that the Storybook is working fine. Looking at the Chromatic side of things now.

**Comment by expspace** [comment] 2023-11-17 14:39
Same issue for our team. It started to fail yesterday with the first build Nov. 16, 2023, 7:53 a.m.

**Comment by marcusabu** [comment] 2023-11-17 15:10
Same issue here. All builds are failing since this morning. Getting the error as described by @dvasyliev

**Comment by cgbl-90** [comment] 2023-11-17 15:12
Can you try to run a new build? We just released a fix to resolve this issue.

**Comment by marcusabu** [comment] 2023-11-17 15:20
@cgbl-90 Ran a new build (using Chromatic CLI v9.1.0) but same error for me unfortunately

**Comment by JonathanKolnik** [comment] 2023-11-17 15:20
@marcusabu it should be released any minute, I'll follow up once it's out!

**Comment by mat-bishop** [comment] 2023-11-17 15:34
looks good now!

**Comment by JonathanKolnik** [comment] 2023-11-17 15:36
Ok @marcusabu @expspace @afternoon2 the fix has been released, please try again

**Comment by afternoon2** [comment] 2023-11-17 15:37
works 🎉 thank you very much 🤗

**Comment by JonathanKolnik** [comment] 2023-11-17 15:40
Awesome, sorry for the trouble here!

**Comment by expspace** [comment] 2023-11-17 16:01
Working now thanks for the fix! 🎉

**Comment by shrink** [comment] 2023-11-17 17:42
For future incidents like this, it would be great if you could please publish acknowledgements to [your status page](https://status.chromatic.com/) and provide a link to the status page in the error message. Thank you :)

**Comment by tevanoff** [comment] 2023-11-17 20:07
@shrink thanks, you're absolutely right! We did add a retroactive update but will strive to add an update faster next time.

Thanks @JonathanKolnik for the quick fix! I'll close this one out now.

**Closed by tevanoff** 2023-11-17 20:07 UTC
Labels: bug, needs triage

**Comment by kim-fransson** [comment] 2023-11-20 08:19
Works here too, thanks for fixing ❤️

**Comment by goodwin64** [comment] 2024-04-26 12:41
In our case upgrading the `@storybook/jest` from `0.1.0` to `0.2.3` helped.

**Comment by Rutulpatel7077** [comment] 2024-08-08 15:08
Experiencing this now, worked yesterday but not now
