### ISSUE TITLE
enable a `working-directory` option for the github action

### ISSUE THREAD

**Issue by travi** [chromaui/chromatic-cli#274] opened 2021-02-05 17:00 UTC
we would like to use [your github action](https://github.com/chromaui/action) for our components in our monorepo. only one of the projects in our monorepo will send data to chromatic, so we want to execute the chromatic-cli from that directory.

could you expose an option to enable this, similar to how [you can define for `run` steps](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun) or [how some other actions have enabled it](https://github.com/bahmutov/npm-install#subfolders)?

**Comment by deebov** [comment] 2021-02-12 11:47
hey @travi 
I had the same issue. chromatic action ignores the default working-directory. But you pass it directly to the action like this:
![image](https://user-images.githubusercontent.com/28673719/107764413-009d8080-6d52-11eb-9efa-bdab4ba55750.png)

**Comment by tmeasday** [comment] 2021-02-18 01:28
I think this is a dupe of: https://github.com/chromaui/chromatic-cli/issues/197

**Closed by tmeasday** 2021-02-18 01:28 UTC
