### ISSUE TITLE
Node 18 Support

### ISSUE THREAD

**Issue by davidhousedev** [chromaui/chromatic-cli#628] opened 2022-08-15 13:47 UTC
We encountered an issue with the `chromatic-cli` as we attempted to upgrade to Node 18. See below

```
Run chromaui/action@v1

Chromatic CLI v6.7.4
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********ea3b'
Retrieving git information
Retrieved git information
    → Commit '1a0c613' on branch 'our-branch-name-here'; found 2 parent builds
Collecting Storybook metadata
Collected Storybook metadata
    → ; no supported addons found
Initializing build
Initialized build
    → Build 164 initialized
Building your Storybook
    → Running command: npm run --silent chromatic:github -- --output-dir /tmp/chromatic--1736-syBD7NO6POLx
The CLI tried to run your chromatic:github script, but the command failed. This indicates a problem with your Storybook. Here's what to do:

- Check the Storybook build log printed below.
- Run npm run chromatic:github or yarn chromatic:github yourself and make sure it outputs a valid Storybook by opening the generated index.html in your browser.
- Review the build-storybook CLI options at https://storybook.js.org/docs/configurations/cli-options/#for-build-storybook

Command failed with exit code 1: npm run --silent chromatic:github -- --output-dir /tmp/chromatic--1736-syBD7NO6POLx

ℹ Spawn settings:
{
  "client": "npm",
  "clientVersion": "8.[15](https://our-github-repo-url/runs/7813009338?check_suite_focus=true#step:4:16).0",
  "nodeVersion": "v18.7.0",
  "platform": "linux",
  "command": "npm",
  "clientArgs": [
    "run",
    "--silent"
  ],
  "scriptArgs": [
    "chromatic:github",
    "--",
    "--output-dir",
    "/tmp/chromatic--1736-syBD7NO6POLx"
  ]
}

ℹ Storybook build output:
/home/runner/work/our-repo/our-repo/build-storybook.log

info @storybook/react v6.5.0-beta.1
info 
info => Cleaning outputDir: /tmp/chromatic--1736-syBD7NO6POLx
info => Loading presets
info => Compiling manager..
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/our-repo/our-repo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/our-repo/our-repo/node_modules/webpack/lib/NormalModule.js:417:[16](https://github.com/butcherbox/our-repo/runs/7813009338?check_suite_focus=true#step:4:17))
    at handleParseError (/home/runner/work/our-repo/our-repo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/work/our-repo/our-repo/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/runner/work/our-repo/our-repo/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/work/our-repo/our-repo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/work/our-repo/our-repo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/runner/work/our-repo/our-repo/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/runner/work/our-repo/our-repo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/runner/work/our-repo/our-repo/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/runner/work/our-repo/our-repo/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.7.0
    → Command failed: npm run --silent chromatic:github -- --output-dir /tmp/chromatic--[17](https://github.com/butcherbox/our-repo/runs/7813009338?check_suite_focus=true#step:4:18)[36](https://github.com/butcherbox/our-repo/runs/7813009338?check_suite_focus=true#step:4:37)-syBD7NO6POLx
```

**Comment by shilman** [comment] 2022-08-16 03:17
Hi @davidhousedev, this looks like a Storybook. To verify that it's unrelated to the Chromatic related, please try running `build-storybook` in the same environment. I expect you'll see the same error as above.

```
npm run build-storybook
```

That would confirm it's a Storybook issue, and you'll have a tighter reproduction. From there, it looks like another user has encountered this issue and found a workaround here, so I'd try that next: https://github.com/storybookjs/storybook/issues/18733

Closing this for now. Please re-open if this doesn't solve things for you. Or if you determine that it's a Storybook issue, please open an issue there.

**Closed by shilman** 2022-08-16 03:17 UTC
