### ISSUE TITLE
Broken Action

### ISSUE THREAD

**Issue by jpulec** [chromaui/chromatic-cli#762] opened 2023-06-13 01:42 UTC
**Bug report**

The current  version of the chromaui/action is busted entirely due to a missing dependency. 

Since there's no history in that repository, there's no way to run this action right now.

```code
Error: Cannot find module '@storybook/csf-tools'
Require stack:
- /home/runner/work/_actions/chromaui/action-next/v1/action/register.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/runner/work/_actions/chromaui/action-next/v1/action/register.js:16:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:[14](https://github.com/chromaui/chromatic-cli/actions/runs/5250198366/jobs/9483883311#step:5:15))
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/chromaui/chromatic-cli/actions/runs/5250198366/jobs/9483883311#step:5:16)9:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:8[22](https://github.com/chromaui/chromatic-cli/actions/runs/5250198366/jobs/9483883311#step:5:23):12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/chromaui/action-next/v1/action/register.js'
  ]
```

Busted CLI run: https://github.com/chromaui/chromatic-cli/actions/runs/5250198366/jobs/9483883311

**Comment by Osseta** [comment] 2023-06-13 03:17
We are seeing the same issue across all builds

**Comment by jwwnz** [comment] 2023-06-13 04:33
We are also seeing the same issue

**Comment by mattseddon** [comment] 2023-06-13 04:38
@tmeasday any chance this was caused by #755 or (less likely) #756?

**Comment by tmeasday** [comment] 2023-06-13 04:47
Thanks folks, I'm looking at this now.

**Comment by tmeasday** [comment] 2023-06-13 04:55
Ok, I think I fixed the issue, can anyone on `action-next` give it a try to confirm? @jpulec

**Comment by tmeasday** [comment] 2023-06-13 05:04
Ok, I think the issue is resolved with #764, sorry about the delay here, I incorrectly thought our CI checks were telling me the action was working!

**Comment by mattseddon** [comment] 2023-06-13 05:04
https://github.com/iterative/vscode-dvc/actions/runs/5251438217/jobs/9486387905?pr=4096 looks fine

**Comment by jwwnz** [comment] 2023-06-13 05:08
Working like a charm for us too, thanks for the speedy fix @tmeasday! 🙌

**Closed** 2023-06-13 05:09 UTC
Labels: bug, needs triage
