### ISSUE TITLE
Github Actions ##[error]non-zero exit code

### ISSUE THREAD

**Issue by ImranAhmed** [chromaui/chromatic-cli#181] opened 2020-08-28 20:19 UTC
Hi,

Seeing the below in my github actions logs with a failure to deploy. Using `"chromatic": "^5.1.0"`.

```
 Run chromaui/action@v132s
    exitOnceUploaded: true
Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
    buildScriptName: build-storybook
    exitZeroOnChanges: true
    exitOnceUploaded: true

Chromatic CLI v5.1.0
https://www.chromatic.com/docs/cli

Cannot read property 'scripts' of undefined
##[error]non-zero exit code
```

Build file
```
name: Run Chromatic

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: chromaui/action@v1
              with:
                  token: ${{ secrets.CHROMATIC_ACCESS_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-storybook
                  exitZeroOnChanges: true
                  exitOnceUploaded: true
```

**Comment by tmeasday** [comment] 2020-09-25 01:55
Hi @ImranAhmed did you figure this issue out? Sorry it slipped through the cracks.

**Comment by ImranAhmed** [comment] 2020-09-25 12:24
Hi,

Thanks for chasing up @tmeasday 

Just tried again and got this error.

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at readFile (fs.js:295:10)
    at go$readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:7:14)
    at Object._readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/jsonfile/index.js:19:58)
    at Object._readFile [as readFile] (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:20:45)
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:66:42)
    at async Promise.all (index 0)`

My build file:


```
name: Run Chromatic

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory:  web-app
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: chromaui/action@v1
              with:
                  token: ${{ secrets.CHROMATIC_ACCESS_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-storybook
                  exitZeroOnChanges: true
                  exitOnceUploaded: true

```

**Comment by thelfensdrfer** [comment] 2020-10-19 20:42
I got the same error. I thought the reason could be the checkout@v2 but I still get the same error with this action:

```yml
name: 'Publish storybook to chromatic'

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$FONTAWESOME_AUTH_TOKEN" > .npmrc'
        shell: bash
        env:
          FONTAWESOME_AUTH_TOKEN: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}
      - run: yarn install
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
```

Error:

```
Error: The "path" argument must be one of type string, Buffer, or URL. Received type object
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at readFile (fs.js:295:10)
    at go$readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:118:14)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:7:14)
    at Object._readFile (/home/runner/work/_actions/chromaui/action/v1/node_modules/jsonfile/index.js:19:58)
    at Object._readFile [as readFile] (/home/runner/work/_actions/chromaui/action/v1/node_modules/universalify/index.js:20:45)
    at /home/runner/work/_actions/chromaui/action/v1/action/main.js:120:53
    at step (/home/runner/work/_actions/chromaui/action/v1/action/main.js:44:23)
Error: The "path" argument must be one of type string, Buffer, or URL. Received type object
```

**Comment by tmeasday** [comment] 2020-10-21 09:22
Hmm, the error is coming from this line: https://github.com/chromaui/chromatic-cli/blob/67709ac71f4d4bc19ded8784d44e7e5c90edc809/action/main.ts#L69

`pkgUp` claims to return a String or `null`, so not sure what's going on there.

Do you have a `package.json` at the root of your project?

**Comment by thelfensdrfer** [comment] 2020-10-21 09:24
I do not (https://github.com/familie-engels-briefe/webapp - `frontend` subdirectory). I thought the `working-directory` parameter would take care of that.

**Comment by ImranAhmed** [comment] 2020-10-21 09:26
Yes, here is the package json

```
{
    "name": "web-app",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "build": "next build",
        "build-storybook": "build-storybook",
        "dev": "next dev",
        "lint": "eslint */**/*.{js,ts,tsx} --quiet --fix",
        "lint:buildserver": "eslint */**/*.{js,ts,tsx} --quiet' --quiet",
        "sort-package": "npx sort-package-json",
        "start": "next start",
        "storybook": "start-storybook -s ./public -p 6006",
        "test": "jest --passWithNoTests",
        "test:watch": "jest --watchAll"
    },
    "husky": {
        "hooks": {
            "pre-commit": "pretty-quick --staged"
        }
    },
    "dependencies": {
        "@auth0/nextjs-auth0": "^0.15.0",
        "@material-ui/core": "^4.11.0",
        "@material-ui/icons": "^4.9.1",
        "@types/styled-components": "^5.1.3",
        "babel-plugin-styled-components": "^1.11.1",
        "clsx": "^1.1.1",
        "date-fns": "^2.16.1",
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.2",
        "isomorphic-unfetch": "^3.0.0",
        "lodash": "^4.17.20",
        "next": "9.5.3",
        "pg": "^8.3.2",
        "pg-promise": "^10.5.8",
        "react": "16.13.1",
        "react-dom": "16.13.1",
        "react-test-renderer": "^16.13.1",
        "sass": "^1.26.10",
        "shortid": "^2.2.15",
        "styled-components": "^5.2.0",
        "swr": "^0.3.3",
        "title-case": "^3.0.2",
        "uuid": "^8.3.0",
        "voca": "^1.4.0"
    },
    "devDependencies": {
        "@babel/core": "^7.11.6",
        "@storybook/addon-actions": "^6.0.22",
        "@storybook/addon-essentials": "^6.0.22",
        "@storybook/addon-links": "^6.0.22",
        "@storybook/react": "^6.0.22",
        "@testing-library/jest-dom": "^5.1.0",
        "@testing-library/react": "^9.4.0",
        "@types/auth0": "^2.20.5",
        "@types/enzyme": "^3.10.5",
        "@types/enzyme-adapter-react-16": "^1.0.6",
        "@types/jest": "^26.0.6",
        "@types/lodash": "^4.14.161",
        "@types/node": "^14.0.27",
        "@types/pg-promise": "^5.4.3",
        "@types/react": "^16.9.43",
        "@types/react-test-renderer": "^16.9.2",
        "@types/uuid": "^8.3.0",
        "@types/voca": "^1.4.0",
        "@typescript-eslint/eslint-plugin": "^3.7.0",
        "@typescript-eslint/parser": "^4.1.0",
        "babel-jest": "^26.3.0",
        "babel-loader": "^8.1.0",
        "chromatic": "^5.1.0",
        "eslint": "^7.8.1",
        "eslint-config-airbnb": "^18.2.0",
        "eslint-config-prettier": "^6.11.0",
        "eslint-plugin-import": "^2.22.0",
        "eslint-plugin-jsx-a11y": "^6.3.1",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-react": "^7.20.6",
        "husky": "^4.2.5",
        "jest": "^26.4.2",
        "prettier": "^2.0.5",
        "pretty-quick": "^2.0.1",
        "react-is": "^16.13.1",
        "ts-jest": "^26.1.3",
        "typescript": "^4.0.2"
    }
}
```

**Comment by tmeasday** [comment] 2020-10-21 23:59
Hmm, ok I guess this is likely the issue, we will try and reproduce.

**Comment by tmeasday** [comment] 2020-10-22 00:18
I think maybe this is a dupe of https://github.com/chromaui/chromatic-cli/issues/197?

**Comment by thelfensdrfer** [comment] 2020-10-27 15:15
Yes it is, you are right.

**Comment by tmeasday** [comment] 2020-10-27 23:26
Ok, I'll close this for simplicity then, thanks for the reports.

**Closed by tmeasday** 2020-10-27 23:26 UTC
Labels: bug, customer reported
