### ISSUE TITLE
[Bug]: Storybook injecting packageManager pnpm 8.1.0 when you run npm run storybook breaks Chromatic

### ISSUE THREAD

**Issue by stevensacks** [chromaui/chromatic-cli#1054] opened 2024-09-18 10:21 UTC
### Describe the bug

[Storybook Bug Ticket](https://github.com/storybookjs/storybook/issues/29146)

When you run `npm run storybook` on a vite project, it is injecting this into the package.json every single time:
```
"packageManager": "pnpm@8.1.0+sha1.09ebf306075e96037432071992bb00340c263d85"
```

This breaks the Chromatic Github Action. Chromatic fails to build Storybook.

You can build Storybook in a previous step and point Chromatic to `storybook-static`, and you can `npx chromatic` on the CLI locally. It only breaks Chromatic's build of Storybook in the Github Action.

### Reproduction link

https://storybook.js.org/

### Reproduction steps

As stated in the description. Make a vite project and `npm run storybook` and it will inject that line into package.json every time. Running the Chromatic Github Action without adding 

Delete the line from package.json, `npm run storybook`, and it's back again.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v20.17.0/bin/npm <----- active
    pnpm: 8.1.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.139
    Safari: 17.6
  npmPackages:
    @storybook/addon-essentials: 8.3.1 => 8.3.1 
    @storybook/addon-interactions: 8.3.1 => 8.3.1 
    @storybook/addon-links: 8.3.1 => 8.3.1 
    @storybook/blocks: 8.3.1 => 8.3.1 
    @storybook/manager-api: 8.3.1 => 8.3.1 
    @storybook/preview-api: 8.3.1 => 8.3.1 
    @storybook/react: 8.3.1 => 8.3.1 
    @storybook/react-vite: 8.3.1 => 8.3.1 
    @storybook/test: 8.3.1 => 8.3.1 
    @storybook/theming: 8.3.1 => 8.3.1 
    @storybook/types: 8.3.1 => 8.3.1 
    chromatic: 11.10.2 => 11.10.2 
    eslint-plugin-storybook: 0.8.0 => 0.8.0 
    storybook: 8.3.1 => 8.3.1 
    storybook-dark-mode: 4.0.2 => 4.0.2 
    storybook-react-i18next: 3.1.7 => 3.1.7
```

**Comment by codykaup** [comment] 2024-09-23 15:01
Thanks for letting us know @stevensacks! Looks like this is coming from Storybook and was fixed up in `8.3.2`. If you upgrade to that version, are you still seeing the issue?

**Comment by stevensacks** [comment] 2024-09-23 15:44
That’s correct. It’s been fixed in 8.3.2, however, @shilman asked me to open this issue on the chromatic repo for a different reason, so please check with him before closing it.

**Comment by shilman** [comment] 2024-09-23 16:21
@codykaup the fix in Storybook was to explicitly disable corepack when we execute package manager commands from the Storybook CLI.

However, there are presumably many ways in which that line can get added to your package.json, so we should ensure that the chromatic CLI does not crash in those cases.

I'd recommend:
- creating a sample project
- running an earlier version of Storybook CLI and verifying that the corepack line gets added and chromatic crashes 
- updating the Storybook to latest but leaving the corepack line in package.json. If Chromatic still fails, figuring out the root cause and fixing it.

**Comment by codykaup** [comment] 2024-09-23 17:06
@shilman gotcha, that makes sense. I'll see what we can come up with!

**Comment by codykaup** [comment] 2024-09-23 20:09
@stevensacks so I've been playing around with this in a blank project and I can't get it to replicate for some reason. Do you have a repo that has this issue somewhere?

**Comment by stevensacks** [comment] 2024-09-24 12:34
@codykaup https://github.com/gaia-react/remix

You’ll need to downgrade the SB libraries to 8.3.1 before calling npm run storybook.

**Comment by codykaup** [comment] 2024-09-27 15:51
> @codykaup https://github.com/gaia-react/remix
> 
> You’ll need to downgrade the SB libraries to 8.3.1 before calling npm run storybook.

Awesome, thanks @stevensacks! I'm finally able to replicate this! The trick is that you have to _commit_ the `packageManager` field change for it to trigger.

I'll see what we can do to fix this up in the CLI. Thanks again for reporting this!

**Comment by codykaup** [comment] 2024-09-27 16:21
Okay looked further into this and chatted with the team. We believe gracefully handling this case would be more surprising than anything else and are leaning toward leaving the behavior (especially now that it's fixed in Storybook).

We currently use [antfu-collective/ni](https://github.com/antfu-collective/ni) to figure out the right package manager and their priority is:
1. `packageManager` in `package.json`
2. Fallback to the existence of lock files

That feels like the most expected flow so we're going to opt for that preference too.

If this becomes a larger issue for folks though, please let us know and we can take another look at this!

**Closed by codykaup** 2024-09-27 16:21 UTC
Labels: bug
