### ISSUE TITLE
Cannot read property 'scripts' of undefined

### ISSUE THREAD

**Issue by mrlubos** [chromaui/chromatic-cli#180] opened 2020-08-28 11:03 UTC
Hey! I'm not sure if this issue is related to `chromatic-cli` or `chromaui/action`, but there's been a recent update to the Github Action which updated the Chromatic CLI from `5.0.0` to `5.1.0` and suddenly all builds fail with the following error.

```
Run chromaui/action@v1
  with:
    buildScriptName: storybook-build
    exitOnceUploaded: true
    exitZeroOnChanges: true
    projectToken: ***
    token: ***

Chromatic CLI v5.1.0
https://www.chromatic.com/docs/cli

Cannot read property 'scripts' of undefined
##[error]non-zero exit code
```

This is my Github Action setup that used to work before the update

```yaml
- uses: chromaui/action@v1
   with:
     buildScriptName: storybook-build
     exitOnceUploaded: true
     exitZeroOnChanges: true
     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
     token: ${{ secrets.GITHUB_TOKEN }}
```

And `package.json`

```json
"storybook-build": "node ./scripts/storybook-build",
```

You can see the linked issue [here](https://github.com/chromaui/action/issues/49)

**Comment by ndelangen** [comment] 2020-08-28 11:28
error seems to originate from:
https://github.com/chromaui/chromatic-cli/blame/6063fba7425a40c2485802fea63152422b83dcfd/CHANGELOG.md#L5

**Comment by ndelangen** [comment] 2020-08-28 11:29
I'm investigating this right now.

**Comment by ndelangen** [comment] 2020-08-28 11:49
I found a fix
​I will be releasing a patch asap

**Comment by ndelangen** [comment] 2020-08-28 11:52
The problem is in the action repo, will close this

**Closed by ndelangen** 2020-08-28 11:52 UTC
